import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Toaster } from "sonner";
import Header from "@/components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <Toaster
            position="top-right"
            richColors
            closeButton
            gap={10}
            toastOptions={{
              classNames: {
                toast: "!rounded-[0px]",
                title: "!text-[15px]/4.75 font-medium",
                description:
                  "!text-neutral-700 dark:!text-white !text-[14px]/4.25",
                actionButton: "!rounded-[3px]",
                success:
                  "dark:!bg-green-600/50 !bg-green-200/50 backdrop-blur-xl  !border-green-300",
                info: "dark:!bg-blue-600/50 !bg-blue-200/50 backdrop-blur-xl !border-blue-300 dark:!text-blue-300",
                warning:
                  "dark:!bg-orange-600/50 !bg-orange-200/50 backdrop-blur-xl   !border-orange-300 !text-orange-500 dark:!text-orange-300",
                error:
                  "dark:!bg-red-600/50 !bg-red-200/50 backdrop-blur-xl   !border-red-300 ",
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
